### PR TITLE
Fix detection of Firefox on iPad

### PR DESCRIPTION
**Pull request by nono**
Provide a general description of the changes in your pull request. If this pull request fixes a known issue, please tag it as well (e.g.: `Fixes #1`).

Before submitting a PR make sure the following things have been done (and denote this by checking the relevant checkboxes):

- [X] The commits are consistent with the [contribution guidelines](../CONTRIBUTING.md).
- [X] You've added tests (if possible) to cover your change(s).
- [X] All tests and style checkers are passing (`make ci`).
- [X] You've updated the [changelog](../CHANGELOG.md).
- [ ] You've updated the [readme](../README.md) (if relevant).

Thanks for contributing to user_agent!

### CODE REVIEW

**Comment by nono** [comment]
By the way, it is quite hard to put a link to the commit in the Changelog, as the commit sha1 can change with a rebase before integrating the master branch.

**Comment by nono** [comment]
And maybe the contribution guidelines should talk of signing the commits (or disabling this rule of git-validation), as most git users don't know about that.

But, globally, I would like to thank you for the Makefile and the contribution guidelines. They are helpful for contributors like me :+1:

**Comment by mssola** [comment]
> By the way, it is quite hard to put a link to the commit in the Changelog, as the commit sha1 can change with a rebase before integrating the master branch.

No worries, I can do that afterwards when preparing a new release.

> And maybe the contribution guidelines should talk of signing the commits (or disabling this rule of git-validation), as most git users don't know about that.

Good point!

**Comment by mssola** [comment]
Thanks!

**Comment by mssola** [comment]
> Good point!

Done. See 07df220f8b87fe68a00efa2a3c18610acf1eab08.

**Pull request merged**
