### PR TITLE
travis: clean go versions

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by mssola** [comment]
I didn't know about this 😄 Could you also add it on patch-level releases ? (e.g. 1.6.x)

**Comment by dvrkps** [comment]
Yes, you can.
"tip" is not listed, but also valid.
"master" compile from source and has much longer build time.
https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use

**Comment by mssola** [comment]
@dvrkps yeah I know. I was asking if you could add patch-level releases on this PR as well 😉

**Comment by dvrkps** [comment]
@mssola that was second guess :) 
Sure, i will do.
 
May i sent it in another PR?
This was from web directly. I don't know how to add new commit to this PR.

What with 1.x and 1.9.x ? Both, only one ? which one ?

**Comment by mssola** [comment]
> This was from web directly. I don't know how to add new commit to this PR.

Simply add a new commit to this branch. Github will happily add the commit to this PR.

> What with 1.x and 1.9.x ? Both, only one ? which one ?

I'd say both. And also add the patch-level versions for the others (e.g. 1.5.x)

**Comment by dvrkps** [comment]
Done.

Travis use go 1.7.4 for all go versions < 1.4

May i strip that versions off ?

**Comment by mssola** [comment]
> Travis use go 1.7.4 for all go versions < 1.4

Really? That's sad. Ok, feel free to remove those versions then.

**Comment by mssola** [comment]
@dvrkps nice!. Now, could you squash your three commits into a single one (since they all refer to the same change anyways) ?

**Comment by dvrkps** [comment]
I think "PR merge button" has that options.

**Comment by mssola** [comment]
@dvrkps you are totally right. Thanks! 👍

**Pull request merged**
