### PR TITLE
Adds the Adsense bot (mobile)

### PR DESCRIPTION
**Pull request by rvflash**
According to the following list of Google crawlers, I have changed the detection of Google mobile crawlers to deal with the one of Google Ads.
> [Google crawlers (user agents)](https://support.google.com/webmasters/answer/1061943)

### CODE REVIEW

**Comment by mssola** [comment]
The second commit is unrelated. Could you push again without this commit? It looks great for the rest. Thanks :+1:

**Comment by rvflash** [comment]
Ok, it's done.

**Comment by mssola** [comment]
Could you squash your commits ?

**Comment by rvflash** [comment]
Hi @mssola, you must be able to do it by choosing on merge the "Squash and merge" option on the pull request on GitHub.

**Comment by mssola** [comment]
@rvflash I always forget about this option :sweat_smile:

**Comment by rvflash** [comment]
No worries, thank you!

**Pull request merged**
